package com.didar.ecomapp.repositories;

import com.didar.ecomapp.models.Product;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface ProductRepository extends JpaRepository<Product, Long> {
    Product save(Product p); // the attributes that are automatically
    //  generated by DB will not be in the param, but will be there in
    // returned object


    @Override
    List<Product> findAll();

    Product findByIdIs(Long id);
}
